final routeName = {
  '/login': 'login',
  '/register': 'register',
  '/verify_account': 'verify_account',
  '/forgot_password': 'forgot_password',
  '/reset_password': 'reset_password',
  '/home': 'home',
  '/tutor/all': 'tutor_all',
  '/schedule': 'schedule',
  '/schedule/detail': 'schedule_detail',
  '/schedule/history': 'schedule_history',
  '/waitingroom': 'waitingroom',
  '/meeting': 'meeting',
  '/courses': 'courses',
  '/ebook': 'ebook',
  '/settings': 'settings',
};
